name: Build & Test

on: [push, pull_request]

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo fmt
      run: cargo fmt --all -- --check
   
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo clippy
      run: |
        sudo apt-get install -y tesseract-ocr
        cargo clippy --all -- -D warnings
  
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo test
      run: |
        sudo apt-get install -y tesseract-ocr
        cargo test
